version: "3.8"
services:
  web_app:
   image: spring
   restart: always
   container_name: spring_container
   ports:
   - 8099:8099
   environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://msyqldb:3307/spring
    SPRING_DATASOURCE_USERNAME: admin
    SPRING_DATASOURCE_PASSWORD: root
   depends_on:
    - mysqldb
    
   
  mysqldb:
   image: mysql
   restart: always
   ports:
   - 3307:3306
   environment:
    MYSQL_USER: admin
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: spring
    MYSQL_ROOT_PASSWORD: root-123
   